// <auto-generated />
namespace StaffMembers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddStaffMembers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStaffMembers));
        
        string IMigrationMetadata.Id
        {
            get { return "201602281356337_AddStaffMembers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
