// <auto-generated />
namespace StaffMembers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddStaffMembers4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStaffMembers4));
        
        string IMigrationMetadata.Id
        {
            get { return "201602281533031_AddStaffMembers4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
